lane :test do
  update_version(
    plist: "path/to/Info.plist",
    version: "1.0.0",
    build_version: 1234
  )
  update_version(
    plist: "path/to/Info.plist",
    version: "1.0.0"
  )
  update_version(
    plist: "path/to/Info.plist",
    build_version: 1234
  )
end
