lane :test do
  set_version(
    plist: "path/to/Info.plist",
    version: "1.0.0",
    build_version: "1234"
  )
  set_version(
    plist: "path/to/Info.plist",
    version: "1.0.0"
  )
  set_version(
    plist: "path/to/Info.plist",
    build_version: "1234"
  )
end
